# -*- coding: utf-8 -*-
"""Introduction to SQL sub-queries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/lucasmoratof/sql-projects/blob/master/Introduction_to_SQL_sub_queries.ipynb

### Introduction to SQL Sub-Queries

This notebook explore the basics of the use of sub-queries with SQL
"""

# Publicly available SQL code practice shared by:      Chilin Tang, Data & Analytics, Digitas Singapore, chilin.tang@digitas.com

# Solution:   This is a simple SQL exercise, which:
#             a.  Inputs number of goals won by 3 different soccer teams
#             b.  Calculates average number of goals
#             c.  Queries teams which had won more than 50 goals on average

# Date of publication:  1 April 2022

# CREATING THE TABLE
import sqlite3

conn = sqlite3.connect('test.db')
print("Opened database successfully");

conn.execute('''
CREATE TABLE IF NOT EXISTS team_data(team text, 
                      country text, 
                      season integer, 
                      total_goals integer);''')

conn.commit()

print("Table created successfully");

# conn.close()

# INSERTING VALUES

conn.execute("INSERT INTO team_data VALUES('Real Madrid', 'Spain', 2019, 53);")
conn.execute("INSERT INTO team_data VALUES('Barcelona', 'Spain', 2019, 47);")
conn.execute("INSERT INTO team_data VALUES('Arsenal', 'UK', 2019, 52);")
conn.execute("INSERT INTO team_data VALUES('Real Madrid', 'Spain', 2018, 49);")
conn.execute("INSERT INTO team_data VALUES('Barcelona', 'Spain', 2018, 45);")
conn.execute("INSERT INTO team_data VALUES('Arsenal', 'UK', 2018, 50 );")

conn.commit()

# Average goal by team

conn = sqlite3.connect('test.db')

cursor = conn.execute(''' SELECT team,
                            AVG(total_goals) AS avg_goals
                          FROM team_data
                          GROUP BY team;''')

for row in cursor:
  print("Average goals by teams")
  print(row)
conn.close()

# Now, the correct query, using the appropriate sub-query

conn = sqlite3.connect('test.db')

cursor = conn.execute(''' SELECT team_name, avg_goals
                          FROM (

                          -- Here we make our sub-query:
                            SELECT team AS team_name,
                            AVG(total_goals) AS avg_goals
                            FROM team_data
                            GROUP BY team) tp
                          -- End of the sub-query
                          
                          WHERE avg_goals > 50;''')

for row in cursor:
  print(row)
conn.close()

"""That's it, this code should be used as a complement to the article  """